local ffi = require 'ffi'
local UI = require 'imgui.imgui'

local Style = {}

function Style.setup()
    local style = UI.GetStyle()
    local colors = style.Colors

    local sty = engine_cfg.editor.style
    style.WindowPadding     = UI.ImVec2(sty.windowPadding.x, sty.windowPadding.y)
    style.FramePadding      = UI.ImVec2(sty.framePadding.x, sty.framePadding.y)
    style.CellPadding       = UI.ImVec2(sty.cellPadding.x, sty.cellPadding.y)
    style.ItemSpacing       = UI.ImVec2(sty.itemSpacing.x, sty.itemSpacing.y)
    style.ItemInnerSpacing  = UI.ImVec2(sty.itemInnerSpacing.x, sty.itemInnerSpacing.y)
    style.TouchExtraPadding = UI.ImVec2(sty.touchExtraPadding.x, sty.touchExtraPadding.y)
    style.IndentSpacing     = sty.indentSpacing    
    style.ScrollbarSize     = sty.scrollbarSize    
    style.GrabMinSize       = sty.grabMinSize      
    style.WindowBorderSize  = sty.windowBorderSize 
    style.ChildBorderSize   = sty.childBorderSize  
    style.PopupBorderSize   = sty.popupBorderSize  
    style.FrameBorderSize   = sty.frameBorderSize  
    style.TabBorderSize     = sty.tabBorderSize    
    style.LogSliderDeadzone = sty.logSliderDeadzone
    style.WindowRounding    = sty.windowRounding   
    style.ChildRounding     = sty.childRounding    
    style.FrameRounding     = sty.frameRounding    
    style.PopupRounding     = sty.popupRounding    
    style.ScrollbarRounding = sty.scrollbarRounding
    style.GrabRounding      = sty.grabRounding     
    style.TabRounding       = sty.tabRounding
    local function cvt(c) return UI.ImVec4(c.a, c.g, c.b, c.r) end
    colors[ffi.C.ImGuiCol_Text]                     = cvt(sty.text                 )
    colors[ffi.C.ImGuiCol_TextDisabled]             = cvt(sty.textDisabled         )
    colors[ffi.C.ImGuiCol_WindowBg]                 = cvt(sty.windowBg             )
    colors[ffi.C.ImGuiCol_ChildBg]                  = cvt(sty.childBg              )
    colors[ffi.C.ImGuiCol_PopupBg]                  = cvt(sty.popupBg              )
    colors[ffi.C.ImGuiCol_Border]                   = cvt(sty.border               )
	colors[ffi.C.ImGuiCol_BorderShadow]             = cvt(sty.borderShadow         )
    colors[ffi.C.ImGuiCol_FrameBg]                  = cvt(sty.frameBg              )
    colors[ffi.C.ImGuiCol_FrameBgHovered]           = cvt(sty.frameBgHovered       )
    colors[ffi.C.ImGuiCol_FrameBgActive]            = cvt(sty.frameBgActive        )
    colors[ffi.C.ImGuiCol_TitleBg]                  = cvt(sty.titleBg              )
    colors[ffi.C.ImGuiCol_TitleBgActive]            = cvt(sty.titleBgActive        )
    colors[ffi.C.ImGuiCol_TitleBgCollapsed]         = cvt(sty.titleBgCollapsed     )
    colors[ffi.C.ImGuiCol_MenuBarBg]                = cvt(sty.menuBarBg            )
    colors[ffi.C.ImGuiCol_ScrollbarBg]              = cvt(sty.scrollbarBg          )
    colors[ffi.C.ImGuiCol_ScrollbarGrab]            = cvt(sty.scrollbarGrab        )
    colors[ffi.C.ImGuiCol_ScrollbarGrabHovered]     = cvt(sty.scrollbarGrabHovered )
    colors[ffi.C.ImGuiCol_ScrollbarGrabActive]      = cvt(sty.scrollbarGrabActive  )
    colors[ffi.C.ImGuiCol_CheckMark]                = cvt(sty.checkMark            )
    colors[ffi.C.ImGuiCol_SliderGrab]               = cvt(sty.sliderGrab           )
    colors[ffi.C.ImGuiCol_SliderGrabActive]         = cvt(sty.sliderGrabActive     )
    colors[ffi.C.ImGuiCol_Button]                   = cvt(sty.button               )
    colors[ffi.C.ImGuiCol_ButtonHovered]            = cvt(sty.buttonHovered        )
    colors[ffi.C.ImGuiCol_ButtonActive]             = cvt(sty.buttonActive         )
    colors[ffi.C.ImGuiCol_Header]                   = cvt(sty.header               )
    colors[ffi.C.ImGuiCol_HeaderHovered]            = cvt(sty.headerHovered        )
    colors[ffi.C.ImGuiCol_HeaderActive]             = cvt(sty.headerActive         )
    colors[ffi.C.ImGuiCol_Separator]                = cvt(sty.separator            )
    colors[ffi.C.ImGuiCol_SeparatorHovered]         = cvt(sty.separatorHovered     )
    colors[ffi.C.ImGuiCol_SeparatorActive]          = cvt(sty.separatorActive      )
    colors[ffi.C.ImGuiCol_ResizeGrip]               = cvt(sty.resizeGrip           )
    colors[ffi.C.ImGuiCol_ResizeGripHovered]        = cvt(sty.resizeGripHovered    )
    colors[ffi.C.ImGuiCol_ResizeGripActive]         = cvt(sty.resizeGripActive     )
    colors[ffi.C.ImGuiCol_Tab]                      = cvt(sty.tab                  )
    colors[ffi.C.ImGuiCol_TabHovered]               = cvt(sty.tabHovered           )
    colors[ffi.C.ImGuiCol_TabActive]                = cvt(sty.tabActive            )
    colors[ffi.C.ImGuiCol_TabUnfocused]             = cvt(sty.tabUnfocused         )
    colors[ffi.C.ImGuiCol_TabUnfocusedActive]       = cvt(sty.tabUnfocusedActive   )
    colors[ffi.C.ImGuiCol_DockingPreview]           = cvt(sty.dockingPreview       )
    colors[ffi.C.ImGuiCol_DockingEmptyBg]           = cvt(sty.dockingEmptyBg       )
    colors[ffi.C.ImGuiCol_PlotLines]                = cvt(sty.plotLines            )
    colors[ffi.C.ImGuiCol_PlotLinesHovered]         = cvt(sty.plotLinesHovered     )
    colors[ffi.C.ImGuiCol_PlotHistogram]            = cvt(sty.plotHistogram        )
    colors[ffi.C.ImGuiCol_PlotHistogramHovered]     = cvt(sty.plotHistogramHovered )
    colors[ffi.C.ImGuiCol_TableHeaderBg]            = cvt(sty.tableHeaderBg        )
    colors[ffi.C.ImGuiCol_TableBorderStrong]        = cvt(sty.tableBorderStrong    )
    colors[ffi.C.ImGuiCol_TableBorderLight]         = cvt(sty.tableBorderLight     )
    colors[ffi.C.ImGuiCol_TableRowBg]               = cvt(sty.tableRowBg           )
    colors[ffi.C.ImGuiCol_TableRowBgAlt]            = cvt(sty.tableRowBgAlt        )
    colors[ffi.C.ImGuiCol_TextSelectedBg]           = cvt(sty.textSelectedBg       )
    colors[ffi.C.ImGuiCol_DragDropTarget]           = cvt(sty.dragDropTarget       )
    colors[ffi.C.ImGuiCol_NavHighlight]             = cvt(sty.navHighlight         )
    colors[ffi.C.ImGuiCol_NavWindowingHighlight]    = cvt(sty.navWindowingHighlight)
    colors[ffi.C.ImGuiCol_NavWindowingDimBg]        = cvt(sty.navWindowingDimBg    )
    colors[ffi.C.ImGuiCol_ModalWindowDimBg]         = cvt(sty.modalWindowDimBg     )
end

return Style
