-- Copyright (c) 2022-2023 Mario "Neo" Sieg. All Rights Reserved.

local SOURCE = 'media'
local TARGET = 'media/scripts/system/fsregistry.lua'

print('Generating fsregistry file: '..TARGET)

-- Create list of ALL file and directories within ../media/*

local function dirtree(dir)
    local dirs = {}
    local function yieldtree(dir)
        for entry in lfs.dir(dir) do
            if entry ~= '.' and entry ~= '..' then
                local path = dir..'/'..entry
                local attribs = lfs.attributes(path)
                if attribs.mode == 'directory' then
                    table.insert(dirs, path)
                    yieldtree(path)
                else
                    coroutine.yield(path)
                end
            end
        end
    end
    return coroutine.wrap(function() yieldtree(dir) end), dirs
end

local files = {
    'media'
}

for filename, _ in dirtree(SOURCE) do
    table.insert(files, filename)
end

local code = '-- Autogenerated - do NOT edit.\nlocal REQUIRED_FILES = {\n'

for _, entry in ipairs(files) do
    code = code..'\t\''..entry..'\',\n'
end

code = code..'}\n\nreturn REQUIRED_FILES\n'

local file = io.open(TARGET, 'w')
file:write(code)

print('Generated fsregistry file: '..TARGET..' with '..#files..' entries.')
