#  Copyright (c) 2022-2023 Mario "Neo" Sieg. All Rights Reserved.


import glob

# create list of ALL file and directories within ../media/*

files = glob.glob("media/**/*", recursive=True)

lua = "-- Autogenerated - do NOT edit.\nlocal REQUIRED_FILES = {\n"

for f in files:
    f = f.replace("media/", "media/").replace("\\", "/")
    lua += '\t\'' + f + '\',\n'

lua += '}\n\nreturn REQUIRED_FILES\n'

with open("media/scripts/system/fsregistry.lua", "w") as f:
    f.write(lua)

